model:
  name: srnn
  n_spikes_per_timestep: 5
  lif_beta: 0.9
  l1_sz: 56
  num_steps: 5
  encoder:
    name: stal
    n_spikes_per_timestep: 5
    l1_sz: 3072
    l2_sz: 3072
    drop_p: 0.1
    # freeze_weights: True
    # checkpoint_path: weights/stal_mnist_20250525_163322.cpkt
    # checkpoint_path for stal on cifar10: weights/stal_cifar10_20250525_162900.cpkt
    # checkpoint_path for convstal on mnist: weights/stal_mnist_20250525_163322.cpkt

data:
  dataset: cifar10
  data_dir: C:\Users\dzahariev\Desktop\Thesis\Thesis\data

training:
  epochs: 10
  batch_size: 128
  learning_rate: 0.001
  train_val_split_ratio: 1
  loss:
    name: cross_entropy
  logger:
    name: wandb
    save_dir: C:\Users\dzahariev\Desktop\Thesis\Thesis\experiments
    project: thesis_rsnn
  save_weights: True