model:
  name: spikformer
  encoder:
    name: stalps # stalps or sps
    embed_dims: 128
    patch_size: 4
  num_heads: 4
  mlp_ratios: 4
  depths: 6
  sr_ratios: 2

data:
  dataset: mnist # cifar10 or mnist
  data_dir: C:\Users\dzahariev\Desktop\Thesis\Thesis\data

training:
  epochs: 10
  batch_size: 64
  learning_rate: 0.001
  loss:
    name: ce_ss # cross_entropy or ce_ss
    omega: 0.0005 # for ce_ss
    concentration_weight: 4 # for ce_ss
  logger:
    name: wandb
    save_dir: C:\Users\dzahariev\Desktop\Thesis\Thesis\experiments
    project: thesis_hyperparameter_search_spikformer_mnist
  save_weights: True