model:
  name: stal
  n_spikes_per_timestep: 5
  l1_sz: 784 # 16 for mnist, 32 for cifar10
  l2_sz: 784
  drop_p: 0.1

data:
  dataset: mnist # cifar10 or mnist
  data_dir: C:\Users\dzahariev\Desktop\Thesis\Thesis\data

training:
  epochs: 10
  batch_size: 128
  learning_rate: 0.001
  loss:
    name: encoder_loss
  logger:
    name: wandb
    save_dir: C:\Users\dzahariev\Desktop\Thesis\Thesis\experiments
    project: thesis_stal
  save_weights: True